project: 
  type: website
  output-dir: docs
  
website: 
    title: Lauren Gunn-Sandell
    navbar:
      left:
      - index.qmd
      - personal.qmd
      - projects.qmd
      - research.qmd
      - contact.qmd
      
editor: visual

format: 
  html: 
    theme: lux